# Generated by Django 4.2 on 2023-04-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invetory',
            name='total_inbound_ammount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invetory',
            name='total_inbound_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invetory',
            name='total_outbound_ammount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invetory',
            name='total_outbound_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
